import Head from 'next/head'
import { useState } from 'react'
import { DollarSign } from 'react-feather'
import NavBar from '../components/NavBar'
import Pomodoro from "../components/Pomodoro"
import Todo from '../components/Todo'
import Shop from '../components/Shop'
export default function Home() {
  const [coins, setCoins] = useState(0)
  const [activeTab, setActiveTab] = useState("Pomodoro")
  return (
    <>
      <Head>
        <title>Studexify | Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/appIcon.ico" />
      </Head>
      <div className="ml-[75vw] flex bg-ultradark text-coins rounded-full py-3 px-5 w-24 mt-5 justify-between text-2xl">
        <DollarSign size={21} className="mt-1"/>
        <p className="-mt-[0.26rem]">{coins}</p>
      </div>
      <NavBar activeTab={activeTab} setActiveTab={setActiveTab}/>
      {activeTab === "Pomodoro" ? <><Pomodoro setCoins={setCoins}/><Todo setCoins={setCoins}/></> : <Shop coins={coins} setCoins={setCoins}/>}
    </>
  )
}
